# Generated by Django 4.2.3 on 2023-08-01 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=40, null=True)),
                ('nip', models.CharField(blank=True, max_length=40, null=True)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.URLField(blank=True, default='berkas/profil.png', max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Guru',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(blank=True, choices=[('Monday', 'Senin'), ('Tuesday', 'Selasa'), ('Wednesday', 'Rabu'), ('Thursday', 'Kamis'), ('Friday', 'Jumat')], max_length=20, null=True)),
                ('jam', models.TimeField()),
                ('keterangan', models.CharField(blank=True, choices=[('1', 'Jam Ke-1'), ('2', 'Jam Ke-2'), ('3', 'Jam Ke-3'), ('4', 'Jam Ke-4'), ('5', 'Jam Ke-5'), ('6', 'Jam Ke-6'), ('7', 'Jam Ke-7'), ('8', 'Jam Ke-8')], max_length=50, null=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajar.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(blank=True, max_length=20, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tahun_Pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_pelajaran', models.CharField(blank=True, max_length=10, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=40, null=True)),
                ('nip', models.CharField(blank=True, max_length=40, null=True)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.URLField(blank=True, default='berkas/profil.png', max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Waka',
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_guru', models.CharField(blank=True, max_length=50, null=True)),
                ('hadir', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_guru', models.URLField(blank=True, null=True)),
                ('pencapaian', models.CharField(blank=True, max_length=500, null=True)),
                ('id_piket', models.CharField(blank=True, default='tidak ada', max_length=50, null=True)),
                ('foto_piket', models.URLField(blank=True, default='tidak ada', null=True)),
                ('tanggal_absen', models.DateTimeField(auto_now_add=True, null=True)),
                ('jadwal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajar.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Piket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=40, null=True)),
                ('nip', models.CharField(blank=True, max_length=40, null=True)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.URLField(blank=True, default='berkas/profil.png', max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Piket',
            },
        ),
        migrations.AddField(
            model_name='jadwal',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajar.kelas'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajar.semester'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tahun_pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajar.tahun_pelajaran'),
        ),
    ]
